// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuE3HsxROJjzorGXiqAE2x3Xe3bo3pzNk',
    appId: '1:232645023520:web:02d75ffb7951d66f056945',
    messagingSenderId: '232645023520',
    projectId: 'deenflow-ac16f',
    authDomain: 'deenflow-ac16f.firebaseapp.com',
    storageBucket: 'deenflow-ac16f.firebasestorage.app',
    measurementId: 'G-ERBG7N0C7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC28baqyIjroJAf47hIJCOLD_2c2KRhxiU',
    appId: '1:232645023520:android:49ac94a5a1eec5d8056945',
    messagingSenderId: '232645023520',
    projectId: 'deenflow-ac16f',
    storageBucket: 'deenflow-ac16f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7IT6N6McAPWs9yLCyVRj-capKrfNqtI',
    appId: '1:232645023520:ios:dc9131ab43f2e899056945',
    messagingSenderId: '232645023520',
    projectId: 'deenflow-ac16f',
    storageBucket: 'deenflow-ac16f.firebasestorage.app',
    iosBundleId: 'com.example.deenflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7IT6N6McAPWs9yLCyVRj-capKrfNqtI',
    appId: '1:232645023520:ios:dc9131ab43f2e899056945',
    messagingSenderId: '232645023520',
    projectId: 'deenflow-ac16f',
    storageBucket: 'deenflow-ac16f.firebasestorage.app',
    iosBundleId: 'com.example.deenflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuE3HsxROJjzorGXiqAE2x3Xe3bo3pzNk',
    appId: '1:232645023520:web:a8024237cf8a3ee3056945',
    messagingSenderId: '232645023520',
    projectId: 'deenflow-ac16f',
    authDomain: 'deenflow-ac16f.firebaseapp.com',
    storageBucket: 'deenflow-ac16f.firebasestorage.app',
    measurementId: 'G-5QWFH7EF43',
  );
}
